# Generated by Django 5.2.7 on 2025-12-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("series", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("body_style", models.CharField(blank=True, max_length=100, null=True)),
                ("production_year", models.IntegerField()),
                ("cylinders", models.CharField(max_length=10)),
                ("displacement", models.FloatField(blank=True, null=True)),
                ("horsepower", models.IntegerField(blank=True, null=True)),
                ("torque_nm", models.IntegerField(blank=True, null=True)),
                ("fuel", models.CharField(blank=True, max_length=50, null=True)),
                ("top_speed", models.FloatField(blank=True, null=True)),
                ("acceleration", models.FloatField(blank=True, null=True)),
                ("drive_type", models.CharField(blank=True, max_length=50, null=True)),
                ("gearbox", models.CharField(blank=True, max_length=50, null=True)),
                ("unladen_weight", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
