# Generated by Django 5.2.7 on 2025-12-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="segment",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
