# Generated by Django 5.2.7 on 2025-12-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_app", "0002_car_segment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="acceleration",
            field=models.CharField(default="N/A", max_length=20),
        ),
        migrations.AlterField(
            model_name="car",
            name="horsepower",
            field=models.CharField(default="N/A", max_length=50),
        ),
        migrations.AlterField(
            model_name="car",
            name="production_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="top_speed",
            field=models.CharField(default="N/A", max_length=50),
        ),
        migrations.AlterField(
            model_name="car",
            name="torque_nm",
            field=models.CharField(default="N/A", max_length=50),
        ),
        migrations.AlterField(
            model_name="car",
            name="unladen_weight",
            field=models.CharField(default="N/A", max_length=50),
        ),
    ]
